name: Test (Simple)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download dependencies
      run: go mod download

    - name: Run tests with coverage
      run: go test -v -coverprofile=coverage.out ./...

    - name: Display coverage
      run: go tool cover -func=coverage.out

    - name: Build application
      run: go build -v .

    - name: Test Docker build
      run: docker build -t gorssag:test . 